# Generated by Django 4.2.7 on 2024-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
